# General Jekyll Config
url: https://blog.lepine.pro
#url: http://localhost:4000
exclude: [LICENSE, CNAME, README.md, TODO.md, .gitignore, Makefile, Capfile, config]

permalink: :title
lsi: false # articles associés améliorés (lent)
markdown: rdiscount
highlighter: true
paginate: 10
destination: build
gems: [jekyll-paginate]
plugins_dir: [jekyll-paginate]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#22c55e'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: Halleck45
    #bitbucket: philipj
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: Halleck45
    #facebook: zuck
    #tumblr: animalygifs
    linkedin: jean-françois-lépine-6a122726
    #gplus: 110552447039675960964

  name: Jean-François Lépine
  #email: test@example.com
  tagline: "Industrialisation, qualité, PHP"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false



sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/assets/css/all.css"
        - "/site.json"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"