# General Jekyll Config
pygments: true
url: http://blog.lepine.pro
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#006ac1'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: Halleck45
    #bitbucket: philipj
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: Halleck45
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Jean-François Lépine
  #email: test@example.com
  tagline: "Industrialisation, qualité, PHP"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-5363554-7

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
